# Copyright (c) 2009-2010 Fabio Cevasco
# website: http://www.h3rald.com/glyph
# license: MIT

require 'rubygems'
require 'pathname'
require 'yaml'
require 'gli'
require 'extlib'
require 'treetop'
require 'rake'

# Glyph is a Rapid Document Authoring Framework able to produce structured documents 	effortlessly.
module Glyph

	# The directory containing Glyph library files
	LIB = Pathname(__FILE__).dirname.expand_path/'glyph'

	# The directory containing the full Glyph installation
	HOME = LIB/'../../'

	# The directory containing all Glyph tests
	SPEC_DIR = Pathname(__FILE__).dirname.expand_path/'../spec'

	# The directory containing all Glyph Rake tasks
	TASKS_DIR = Pathname(__FILE__).dirname.expand_path/'../tasks'

	require LIB/'system_extensions'
	require LIB/'config'
	require LIB/'node'
	require LIB/'document'
	require LIB/'glyph_language'
	require LIB/'macro_validators'
	require LIB/'macro'
	require LIB/'interpreter'

	# The current version of Glyph
	VERSION = file_load(HOME/'VERSION').strip

	# All the currently-loaded snippets
	SNIPPETS = {}

	# All the currently-loaded macros
	MACROS = {}

	begin
		unless const_defined? :MODE then
			# Glyph's modes: debug/lite/test
			MODE = {:debug => false, :lite => false, :test => false} 
		end
	rescue
	end

	# The main document being generated by Glyph
	@@document = nil

	# Returns true if Glyph is running in test mode
	def self.test?
		MODE[:test]
	end
	
	# Returns true if Glyph is running in "lite" mode
	def self.lite?
		MODE[:lite]
	end

	# Returns true if Glyph is running in debug mode
	def self.debug?
		MODE[:debug]
	end

	# Enable/disables test mode
	# @param [Boolean] mode whether test mode is enabled or not
	def self.debug_mode=(mode)
		MODE[:debug] = mode
	end	

	# Enable/disables lite mode (i.e. the compilation of a single Glyph file)
	# @param [Boolean] mode whether lite mode is enabled or not
	def self.lite_mode=(mode)
		MODE[:lite] = mode
	end

	# The directory of the current Glyph project.
	PROJECT = (Glyph.test?) ? Glyph::SPEC_DIR/"test_project" : Pathname.new(Dir.pwd)

	# Glyph's configuration
	CONFIG = Glyph::Config.new :resettable => true, :mutable => false

	home_dir = Pathname.new(RUBY_PLATFORM.match(/win32|mingw/) ? ENV['HOMEPATH'] : ENV['HOME'])
	SYSTEM_CONFIG = 
		Glyph::Config.new(:file => HOME/'config.yml')
	GLOBAL_CONFIG = 
		Glyph.test? ? Glyph::Config.new(:file => SPEC_DIR/'.glyphrc') : Glyph::Config.new(:file => home_dir/'.glyphrc')
	PROJECT_CONFIG = 
		Glyph::Config.new(:file => PROJECT/'config.yml', :resettable => true) rescue Glyph::Config.new(:resettable => true, :mutable => true)

	# Loads all Rake tasks
	def self.setup
		FileList["#{TASKS_DIR}/**/*.rake"].each do |f|
			load f
		end	
	end

	# Used to access @@document 
	def self.document
		@@document
	end

	# Used to set @@document 
	def self.document=(document)
		@@document = document
	end

	# Returns the value of a configuration setting
	def self.[](setting)
		Glyph::CONFIG.get(setting)
	end

	# Overrides a configuration setting
	# @param [String, Symbol] setting the configuration setting to change
	# @param value the new value
	def self.[]=(setting, value)
		PROJECT_CONFIG.set setting, value
		self.config_refresh
	end

	# Restores Glyph configuration (keeping all overrides and project settings)
	def self.config_refresh
		CONFIG.merge!(SYSTEM_CONFIG.merge(GLOBAL_CONFIG.merge(PROJECT_CONFIG)))
	end

	# Resets Glyph configuration (removing all overrides and project settings)
	def self.config_reset
		Glyph::CONFIG.reset
		Glyph::PROJECT_CONFIG.reset
		self.config_refresh
	end

	# Returns true if the PROJECT constant is set to a valid Glyph project directory
	def self.project?
		children = ["styles", "text", "output", "snippets.yml", "config.yml", "document.glyph"].sort
		actual_children = PROJECT.children.map{|c| c.basename.to_s}.sort 
		(actual_children & children) == children
	end

	# Resets Glyph completely, i.e.:
	# * Re-enables all Glyph Rake tasks
	# * Resets the configuration to system defaults
	# * Clears macros and snippets
	def self.reset
		self.enable_all
		self.config_reset
		MACROS.clear
		SNIPPETS.clear
	end

	# Reenables all Glyph Rake tasks
	def self.enable_all
		Rake::Task.tasks.each {|t| t.reenable }
	end

	# Reenables a Rake task
	# @param [Symbol, String] task the task to enable
	def self.enable(task)
		Rake::Task[task].reenable
	end

	# Reenables and runs a Rake task
	# @param [Symbol, String] task the task to run
	# @param *args the task arguments
	def self.run!(task, *args)
		Rake::Task[task].reenable
		self.run task, *args
	end

	# Runs a Rake task
	# @param [Symbol, String] task the task to run
	# @param *args the task arguments
	def self.run(task, *args)
		Rake::Task[task].invoke *args
	end

	# Defines a new macro
	# @param [Symbol, String] name the name of the macro
	def self.macro(name, &block)
		MACROS[name.to_sym] = block
	end

	# Defines an alias for an existing macro
	# @param [Hash] text the single-key hash defining the alias
	# @example
	# 	{:old_name => :new_name}
	def self.macro_alias(pair)
		name = pair.keys[0].to_sym
		found = MACROS[name]
		if found then
			self.warning "Invalid alias: macro '#{name}' already exists."
			return
		end
		MACROS[name] = MACROS[pair.values[0].to_sym]
	end

	# Compiles a single Glyph file
	# @param [String] src the full or relative path to the source file
	# @param [String] out the full or relative path to the output file
	def self.compile(src, out=nil)
		dir = Pathname.new(src).parent
		Dir.chdir dir.to_s	
		GLI.run ["compile", src, out].compact	
		self.lite_mode = false
	end

	# Converts a text containing Glyph markup language into the current Glyph output target.
	# *Note* Only 'html' is supported as output target for now. 
	# @param [String] text the text to convert
	# @return [String] the converted text
	# @example
	# 	require 'glyph'
	# 	Glyph.filter "section[header[Test]\nA Test section...]"
	def self.filter(text)
		self.lite_mode = true
		self.enable_all
		result = ""
		begin
			Glyph[:quiet] = true
			Glyph.run 'load:all'
			result = Interpreter.new(text).document.output
		rescue Exception => e
			raise if self.debug?
		ensure
			self.lite_mode = false
			Glyph[:quiet] = false
		end
		result
	end

	# Prints a message
	# @param [#to_s] message the message to print
	def self.info(message)
		puts "#{message}" unless Glyph[:quiet]
	end

	# Prints a warning
	# @param [#to_s] message the message to print
	def self.warning(message)
		puts "\nwarning: #{message}" unless Glyph[:quiet]
	end

	# Prints an error
	# @param [#to_s] message the message to print
	def self.error(message)
		puts "\nerror: #{message}" unless Glyph[:quiet]
	end

end

Glyph.setup
